export * from './client'
export * from './endpoints'
export * as authApi from './auth'
export * as userApi from './user'
export * as slotApi from './slot'
export * as adminApi from './admin'
export * as registerApi from './register'